import type { ConfigEnv, PluginOption } from 'vite'
import dayjs from 'dayjs'
import utc from 'dayjs/plugin/utc.js' // https://github.com/iamkun/dayjs/issues/1167
import tz from 'dayjs/plugin/timezone.js'
import { ClientLogger } from '../../client'

dayjs.extend(utc)
dayjs.extend(tz)

export function logAppInfo(configEnv: ConfigEnv): PluginOption {
  const { mode } = configEnv

  const currentBuildTime = dayjs().tz('Asia/Shanghai').format('YYYY-MM-DD HH:mm:ss')

  const logger = new ClientLogger(undefined, true)

  const t = logger.log(
    { text: mode, type: 'success' },
    { text: 'BuildTime', type: 'warn' },
    { text: currentBuildTime, type: 'info' },
  )!

  return {
    name: 'vite:log-app-info',
    enforce: 'post',
    transformIndexHtml: {
      order: 'post',
      handler(html) {
        return {
          html,
          tags: [
            {
              injectTo: 'body',
              children: `// Auto generated by @minko-fe/vite-config\nconsole.log(${t.map((str) => `"${str}"`)});`,
              tag: 'script',
            },
          ],
        }
      },
    },
  }
}
