import type { PluginOption } from 'vite'
import { ClientLogger } from '../../client'

export function logAppInfo(): PluginOption {
  const currentBuildTime = new Date().toLocaleString()

  const logger = new ClientLogger(undefined, true)

  const t = logger.log({ text: 'BuildTime', type: 'success' }, { text: currentBuildTime, type: 'info' })!

  return {
    name: 'vite:log-app-info',
    enforce: 'post',
    transformIndexHtml: {
      order: 'post',
      handler(html) {
        return {
          html,
          tags: [
            {
              injectTo: 'body',
              children: `// Auto generated by @minko-fe/vite-config\nconsole.log(${t.map((str) => `"${str}"`)});`,
              tag: 'script',
            },
          ],
        }
      },
    },
  }
}
